# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdf7aeb73eefb4d28456c941da898df31244eef959128ad093d3603ef8eb1d3d5e00668ead049c76b812ba767ec8e44c9f35f234736fde770ceea8525383be01

test:
  secret_key_base: c846ebdc2858d0a3219cbbeda6e49b76072980b0eff1db33bd351ac0be101b8abe803aad8b3905e05a4fd63ae40e5f444f063dd85a7767b20e76c9cf979babbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
